# This will allow the namespace you define to the kube-system
# namespace to be able to perform dns queries.
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ namespace }}
  name: allow-dns
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
