# This will allow all of the pods within the same namespace to have full access to each other. 
# This can be useful if you have a global deny policy through a project like calico.
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ namespace }}
  name: allow-from-namespace-ing
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
       matchLabels:
         name: {{ namespace }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ namespace }}
  name: allow-from-namespace-egr
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
       matchLabels:
         name: {{ namespace }}
